name: AppEngine Org Policy - Organization Level

env:
  org-name: sentinelman

on:
  push:
    branches:
    - ${{env.org-name}}-main
    - ${{env.org-name}}-dev
    
  pull_request:
    branches:
    - ${{env.org-name}}-main
    - ${{env.org-name}}-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '313.0.0'
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
        
      - name: Deploy
        id: deploy
        run: gcloud resource-manager org-policies set-policy --organization=${{ secrets.org_id_sentinelman }} ./set-${{env.org-name}}-org-policy.yaml
      
      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            #### Deploy Initialization ⚙️\`${{ steps.deploy.outcome }}\`
            <details><summary>Show Deploy</summary>
            < /details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
        
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: status
        if: steps.deploy.outcome == 'failure'
        run: exit 1
        
